complexity:
  CyclomaticComplexMethod:
    allowedComplexity: 33
  LongMethod:
    allowedLines: 158
  LongParameterList:
    allowedConstructorParameters: 11
    allowedFunctionParameters: 11
  NestedBlockDepth:
    allowedDepth: 10
  TooManyFunctions:
    allowedFunctionsPerClass: 19
    allowedFunctionsPerObject: 14

coroutines:
  InjectDispatcher:
    active: false

# Formatting rules are implemented via the ktlint plugin. As ktlint does not allow exceptions, we need to disable
# respective rules completely.
ktlint:
  AnnotationOnSeparateLine:
    active: false
  ArgumentListWrapping:
    active: false
  ChainMethodContinuation:
    active: false
  ChainWrapping:
    active: false
  ClassSignature:
    active: false
  CommentWrapping:
    active: false
  FinalNewline:
    active: false
  FunctionSignature:
    active: false
  ImportOrdering:
    active: false
  Indentation:
    active: false
  MaximumLineLength:
    active: false
  NoBlankLineInList:
    active: false
  NoWildcardImports:
    active: false
  ParameterListWrapping:
    active: false
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
  StringTemplateIndent:
    active: false
  TrailingCommaOnCallSite:
    active: true
    useTrailingCommaOnCallSite: false
  TrailingCommaOnDeclarationSite:
    active: true
    useTrailingCommaOnDeclarationSite: false

naming:
  InvalidPackageDeclaration:
    active: false

performance:
  SpreadOperator:
    active: false

style:
  ForbiddenComment:
    active: false
  ForbiddenMethodCall:
    active: true
    # Use org.eclipse.apoapsis.ortserver.utils.logging.runBlocking to make sure the MDC context is preserved.
    # An exception to that is code where the MDC context is not relevant, e.g., in tests.
    methods: ['kotlinx.coroutines.runBlocking']
    excludes: ['**/cli/**'] # The CLI does not have accees to the utils package, therefore, exclude it for this rule.
  LoopWithTooManyJumpStatements:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  SpacingAfterPackageDeclaration:
    active: true
  ThrowsCount:
    max: 5
  WildcardImport:
    excludeImports:
      - org.eclipse.apoapsis.ortserver.core.plugins.*

ORT:
  OrtImportOrder:
    active: true
  OrtPackageNaming:
    # TODO: Implement package naming check for ort-server.
    active: false
