/*
 * Copyright (C) 2026 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package org.eclipse.apoapsis.ortserver.credentialhelper.common

import okio.BufferedSource
import okio.Path

/**
 * A data class storing the information about the URL for which credentials need to be obtained. The framework matches
 * this URL against the information from a credentials file to find the corresponding credentials. It then passes the
 * outcome of this operation back to the caller. Since the caller may need additional context information to properly
 * handle the request, an instance can carry such a context object. This allows the caller to associate arbitrary
 * information with the request without having to implement its own state management.
 */
data class RequestUrl<C>(
    /**
     * The URL to be authenticated. This is the primary input to the credential helper. Based on the host and the path,
     * it tries to find the best-matching credentials.
     */
    val url: String,

    /**
     * Arbitrary context data to be managed on behalf of the caller. This field is not evaluated, but just passed
     * through to the caller together with the looked up credentials. The caller can use this to construct the final
     * result.
     */
    val context: C
)

/**
 * A data class representing the result of a credential helper invocation. Instances are created by concrete helper
 * implementations. They contain the data to be printed to stdout and the exit code indicating the success status of
 * the operation.
 */
data class CredentialHelperResult(
    /** The output generated by the credential helper. This text is printed to stdout. */
    val output: String,

    /** The exit code when terminating the process. */
    val exitCode: Int
)

/**
 * Type alias for a function that parses the input to a credential helper (from stdin) and extracts a [RequestUrl]
 * object from it. The URL in this object is then matched against the known credentials. Since input can be invalid,
 * the function returns a [Result] to indicate this.
 */
typealias InputReader<C> = (BufferedSource) -> Result<RequestUrl<C>>

/**
 * Type alias for a function that is invoked to produce the output of a credential helper. The function is passed the
 * [RequestUrl] that has been processed and an optional [AuthenticationInfo] object with the resolved credentials. It
 * returns an object with information how to answer the current request.
 */
typealias ResultGenerator<C> = (RequestUrl<C>, AuthenticationInfo?) -> CredentialHelperResult

/**
 * A data class collecting all information to handle a request for the credentials of a specific URL.
 *
 * An instance of this class is passed to the main function of the credentials helper framework. Based on the
 * properties of this object, the function can
 * - process command line arguments
 * - extract the URL in question from the input parameters
 * - determine the file with credentials to read
 * - produce the expected output with the credentials that could be resolved or not.
 */
data class CredentialsRequest<C>(
    /**
     * The function to process the input and to obtain the URL for which credentials are requested. The function is
     * called with a source connected to the standard input of the process.
     */
    val inputReader: InputReader<C>,

    /**
     * The function to generate the result of the credential helper. It is invoked with the credentials that have or
     * have not been found for the URL in question.
     */
    val resultGenerator: ResultGenerator<C>,

    /**
     * The path to the file containing the known credentials. It must point to a file in the format expected by the
     * credential helper framework. While all concrete implementations share the same data format, there are
     * different files for each implementation with individual content.
     */
    val credentialsFile: Path,

    /**
     * The command from the command line that triggers the lookup of credentials. Some implementations support multiple
     * commands (for instance, in the case of Git, these are the commands _get_, _store_, and _erase_). The framework
     * handles only the command to query credentials. Other commands are either ignored (if they are listed in
     * [ignoredCommands]) or cause an error result.
     */
    val credentialCommand: String,

    /**
     * A set with commands that should be ignored by the credential helper. If such a command is encountered, the
     * helper just returns a 0 exit code without further actions.
     */
    val ignoredCommands: Set<String> = emptySet()
)
